### PR TITLE
Avoid to branch in source method

### PR DESCRIPTION
**Pull request by uilianries**
closes https://github.com/bincrafters/community/issues/613
/cc @memsharded

### CODE REVIEW

**Comment by madebr** [comment]
Can't you just patch the sources? No matter what compiler is used?
`.vcxproj` are project file used only by the Visual Studio compiler.

**Comment by memsharded** [comment]
Yes, it is totally ok to patch the sources inconditionally, in the ``source()`` method.

The only rule is that the result of running ``source()`` should be usable from all configurations, because it will be ran just once for all of those said configurations. Patches to .vcproj files that do not affect other builds, it is perfectly valid.

**Comment by uilianries** [comment]
I prefer to keep `source` untouched. For example, when something goes wrong and I need to check the project source files, I read my local copy in source folder. Also, if my patch has some bug, I'll need to download the source again for each new change.

**Comment by madebr** [comment]
I understand.
I did this to cache downloads because the file was 90+MB and was rate limited:
https://github.com/madebr/conan-lunarg_vulkan_sdk/blob/f9cce1cf52fbfcb60d2697e059bacf348f83bad3/conanfile.py#L61-L66

(once lunarg releases a new sdk, I'll open a pr to bincrafters)

**Comment by SSE4** [comment]
@uilianries I am getting the following errors:
```
---------------------------
test_package.exe - System Error
---------------------------
The code execution cannot proceed because glfont.exe was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
```
```
---------------------------
test_package.exe - Bad Image
---------------------------
C:\bincrafters\conan-sdl2_ttf\test_package\build\882726301a296ee1f7f1d98a3db2003150ea70a8\bin\VERSION.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support. Error status 0xc000012f. 
---------------------------
OK   
---------------------------
```
what are these `glfont.exe` and `VERSION.dll`?

**Comment by SSE4** [comment]
@uilianries @Croydon @madebr any ideas so far?

**Comment by uilianries** [comment]
Crazy error, I can't reproduce here. Let me try other profile.

**Comment by madebr** [comment]
My guess on the `glfont.exe` error:
`glfont.exe` and `showfont.exe` are executables built by the Visual Studio solution.
It creates glfont.lib and showfont.lib libraries which were also copied in `package()` and added to `self.package_info.libs` using `tools.collect_libs(self)`.
I believe the test_package linked to this glfont.lib file which caused the first error to display

The `VERSION.DLL` error:
The `package()` method of the Visual Studio compiler was too generic,
it copies all dll's, lib's, ...
`VERSION.DLL` can be found at `source_subfolder/external/freetype-2.4.12/docs/VERSION.DLL`
It is a text file.

I fixed these problems in my local fork: https://github.com/madebr/conan-sdl2_ttf/pull/1
This builds on Appveyor.
This fails to build on my local machine when using the *Package development flow* (see my message on the pr) because I have not installed Windows 8.1 SDK. I do not know how to set the Windows SDK using conan.

**Comment by madebr** [comment]
@uilianries I think I fixed the Visual Studio issues in my pr on my branch. You can merge them in this pr.

**Review by SSE4 — APPROVED** [review]

**Comment by uilianries** [comment]
Amazing! Thanks @madebr @SSE4

**Pull request merged**
